postgres:
    host: postgresql-database
    port: 5432
    user: go-microservice-boilerplate
    password: go-microservice-boilerplate
    database: go-microservice-boilerplate

redis:
    host: redis-database
    port: 6379
    password:
    database: 0

meili:
    host: meilisearch-database
    port: 7700
    key: go-microservice-boilerplate

minio:
    host: minio-database
    port: 9000
    access_key: go-microservice-boilerplate
    secret_key: go-microservice-boilerplate
    secure: false
    bucket: go-microservice-boilerplate
