basePath: /api
definitions:
  github_com_balcieren_go-microservice_pkg_helper.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  proto.GetUserResponse:
    properties:
      age:
        type: integer
      created_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      email:
        type: string
      id:
        type: string
      updated_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      user_name:
        type: string
    type: object
  proto.ListUsersResponse:
    properties:
      rows:
        items:
          $ref: '#/definitions/proto.User'
        type: array
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  proto.User:
    properties:
      age:
        type: integer
      created_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      email:
        type: string
      id:
        type: string
      updated_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      user_name:
        type: string
    type: object
  timestamppb.Timestamp:
    properties:
      nanos:
        description: |-
          Non-negative fractions of a second at nanosecond resolution. Negative
          second values with fractions must still have non-negative nanos values
          that count forward in time. Must be from 0 to 999,999,999
          inclusive.
        type: integer
      seconds:
        description: |-
          Represents seconds of UTC time since Unix epoch
          1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
          9999-12-31T23:59:59Z inclusive.
        type: integer
    type: object
  v1.CreateUserInput:
    properties:
      age:
        type: integer
      email:
        type: string
      username:
        type: string
    required:
    - age
    - email
    - username
    type: object
  v1.UpdateUserInput:
    properties:
      age:
        type: integer
      email:
        type: string
      username:
        type: string
    required:
    - age
    - email
    - username
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample server for Go-Microservice API Documentation.
  title: Go-Microservice API Documentation
  version: "1.0"
paths:
  /v1/users:
    get:
      consumes:
      - application/json
      description: List Users
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Per Page
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/proto.ListUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List Users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: Create User Body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/v1.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: user has created successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create User
      tags:
      - User
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: user has deleted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/proto.GetUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get User
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      - description: Update User Body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateUserInput'
      produces:
      - application/json
      responses:
        "202":
          description: user has updated successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_balcieren_go-microservice_pkg_helper.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - User
schemes:
- http
swagger: "2.0"
